version: '3.8'

services:
  breeder_postgres:
    container_name: breeder-postgres
    image: postgres:alpine
    env_file: backend/.env
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - breeder-postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    networks:
      - webnet

  breeder_api:
    container_name: breeder-backend
    build:
      context: ./backend/
      target: development
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - ${PORT:-3002}:${PORT:-3002}
      - ${DEBUGGER_PORT:-9229}:${DEBUGGER_PORT:-9229}
    depends_on:
      - breeder_postgres
    networks:
      - webnet

  breeder_frontend:
    container_name: breeder-frontend
    build:
      context: ./frontend/
      target: development
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    networks:
      - webnet

volumes: 
  breeder-postgres:
  breeder-backend:
  breeder-frontend:

networks:
  webnet: