
name: breeder-frontend-deployment
on:
  push:
    branches: 
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_deployment.yml"

jobs:    
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} and install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: frontend

      - name: Build
        run: yarn build
        working-directory: frontend

      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git

      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix frontend master`:refs/heads/master --force